import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BenefitsSection from "./pq_nosotros";
import ClassesSection from "./servicios";
import TestimonialsSection from "./testimonios";
import ContactSection from "./contacto";
import FinalCTASection from "./CTA";
import Footer from "./footer";
import Header from "./header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
        <BenefitsSection />
        <ClassesSection />
        <TestimonialsSection />
        <ContactSection />
        <FinalCTASection />
        <Footer />
      </body>
    </html>
  );
}
